-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 13:43:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hwwos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hwwos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hwwos` DEFAULT CHARACTER SET utf8 ;
USE `hwwos` ;

-- -----------------------------------------------------
-- Table `hwwos`.`org`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwwos`.`org` (
  `org_id` VARCHAR(45) NOT NULL,
  `org_name` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `parent_id` VARCHAR(45) NULL,
  PRIMARY KEY (`org_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwwos`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwwos`.`user` (
  `user_id` VARCHAR(45) NOT NULL,
  `user_code` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(64) NULL,
  `org_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_code_UNIQUE` (`user_code` ASC),
  INDEX `fk_user_org_idx` (`org_id` ASC),
  CONSTRAINT `fk_user_org`
    FOREIGN KEY (`org_id`)
    REFERENCES `hwwos`.`org` (`org_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwwos`.`workorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwwos`.`workorder` (
  `wo_id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `wo_content` VARCHAR(1024) NULL,
  `create_time` DATETIME NULL,
  `close_time` DATETIME NULL,
  `status` CHAR(1) NULL COMMENT 'S-Started\nC-closed',
  PRIMARY KEY (`wo_id`),
  INDEX `fk_workorder_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_workorder_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hwwos`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwwos`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwwos`.`privilege` (
  `privilege_id` VARCHAR(45) NOT NULL,
  `privilege_name` VARCHAR(45) NULL,
  PRIMARY KEY (`privilege_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwwos`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwwos`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hwwos`.`user_privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hwwos`.`user_privilege` (
  `user_id` VARCHAR(45) NOT NULL,
  `priv_id` VARCHAR(45) NOT NULL,
  INDEX `fk_user_privilege_user1_idx` (`user_id` ASC),
  INDEX `fk_user_privilege_privilege1_idx` (`priv_id` ASC),
  CONSTRAINT `fk_user_privilege_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hwwos`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_privilege_privilege1`
    FOREIGN KEY (`priv_id`)
    REFERENCES `hwwos`.`privilege` (`privilege_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
